for i in range(2):
    print(f'\nEnter Information for student {i+1}:')
    fname = input('Enater student first name: ')
    midN = input('Enater student mid name: ')
    lastN = input('Enater student last name: ')
    age = int(input('Enater student Age: '))
    address = input('Enater student Address: ')
    phone = input('Enater student phone no.: ')
    college = input('Enater student College Name: ')
    roll = int(input('Enater student Roll no.: '))
    classN = input('Enater student Class: ')
    div = input('Enater student Division: ')
    year = int(input('Enater student Year: '))

for i in range(2):
    print(f'\nInformation Of Student {i+1}:')
    print(f'student first name: {fname}')
    print(f'student mid name: {midN}')
    print(f'Enater student last name: {lastN}')
    print(f'student Age: {age}')
    print(f'student Address: {address}')
    print(f'student phone no.: {phone}')
    print(f' student College Name: {college}')
    print(f' student Roll no.: {roll}')
    print(f' student Class: {classN}')
    print(f' student Division: {div}')
    print(f' student Year: {year}')
